First version. Only valid ISBNs obtained by removing invalid characters (but result not checked for actual existence). Only non-zero ratings. Only users and books that have at least 3 ratings.

Update: U and V generated using wide uniform distribution

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
from scipy.sparse import coo_matrix, csr_matrix

from load_data import load_data
from valid_test_select import valid_test_select
from initialize_model import initialize_mu_b_c
from helpers import get_rmse
from fit_model import fit_model_no_UV, fit_model_full

In [3]:
np.set_printoptions(linewidth=150, precision=6)  # 75, 8

# Loading Data

In [4]:
df = load_data()

In [5]:
df.agg(["min", "max", "nunique", "dtype", "count", "size"])

          userid        isbn   rating
min            2  0000001481        0
max       278854  9998150752       10
nunique   103371      328465       11
dtype      int32      object     int8
count    1135338     1135338  1135338
size     1135338     1135338  1135338

In [6]:
df = df[df.rating > 0]

In [7]:
df.agg(["min", "max", "nunique", "size"])

         userid        isbn  rating
min           8  000003827X       1
max      278854  9997555635      10
nunique   76331      179924      10
size     427261      427261  427261

# Creating Matrix Y

In [8]:
# Encoding userids and isbns as categories (integers 0 to N-1)

user_cats = df.userid.astype("category")
book_cats = df.isbn.astype("category")

In [9]:
# Creating sparse matrix and converting it to pd.DataFrame

Y_sparse = coo_matrix((df.rating.values, (user_cats.cat.codes, book_cats.cat.codes)))
Y = pd.DataFrame(Y_sparse.toarray())

In [10]:
# print("Y shape:", Y.shape)  # (76331, 179924)
# print("total entries:", (Y > 0).sum().sum())  # 427261
# print("avg number of ratings per user:", round((Y > 0).sum(axis=1).mean(), 2))  # 5.6
# print("avg number of ratings per book:", round((Y > 0).sum(axis=0).mean(), 2))  # 2.37

In [11]:
# Filtering out improbably active readers

# np.sort(np.partition((Y > 0).sum(axis=1), -20)[-20:])
Y = Y.loc[(Y > 0).sum(axis=1) < 2000, :]

In [12]:
# Filtering users and books with enough observations

min_rats = 3
old_rows, old_cols = Y.shape
while True:
    Y_pos = Y > 0  # type: ignore
    user_rats = Y_pos.sum(axis=1)  # type: ignore
    book_rats = Y_pos.sum(axis=0)  # type: ignore
    new_rows = (user_rats >= min_rats).sum()
    new_cols = (book_rats >= min_rats).sum()
    # print(new_rows, new_cols)
    Y = Y.loc[user_rats >= min_rats, book_rats >= min_rats]  # type: ignore
    if (old_rows == new_rows) and (old_cols == new_cols):
        break
    old_rows, old_cols = new_rows, new_cols

In [13]:
print("Y shape:", Y.shape)
print("total entries:", (Y > 0).sum().sum())
print("avg number of ratings per user:", round((Y > 0).sum(axis=1).mean(), 2))
print("avg number of ratings per book:", round((Y > 0).sum(axis=0).mean(), 2))

Y shape: (14903, 22661)
total entries: 182612
avg number of ratings per user: 12.25
avg number of ratings per book: 8.06

In [14]:
# Converting Y to numpy array

Y_columns = Y.columns.copy()
Y = Y.to_numpy()

In [15]:
def get_isbn(pos):
    """Given position of column in matrix Y, return the original ISBN."""
    return book_cats.cat.categories[Y_columns[pos]]

# Selecting validation and test sets

In [16]:
Y_train, valid_data, test_data = valid_test_select(Y, 20_000, 20_000, seed=123)

In [17]:
print("Y_train shape:", Y_train.shape)
print("total train entries:", (Y_train > 0).sum().sum())
print("avg. # of train entries per user:", round((Y_train > 0).sum(axis=1).mean(), 2))
print("avg. # of train entries per book:", round((Y_train > 0).sum(axis=0).mean(), 2))
print("users with no ratings:", ((Y_train > 0).sum(axis=1) == 0).sum())
print("books with no ratings:", ((Y_train > 0).sum(axis=0) == 0).sum())

Y_train shape: (14903, 22661)
total train entries: 142612
avg. # of train entries per user: 9.57
avg. # of train entries per book: 6.29
users with no ratings: 50
books with no ratings: 103

# ALS

In [18]:
Y_csr = csr_matrix(Y_train)
Y_csc = Y_csr.tocsc()

## Model with just a training global mean

In [19]:
mu, _, _ = initialize_mu_b_c(Y_train)
print("test rmse of model=mu:", get_rmse(mu, test_data))
# test rmse of model=mu: 1.8087624016357353

test rmse of model=mu: 1.7927095878715544

## Model with only biases

In [20]:
lambda_bias = 4.5
mu, b, c = initialize_mu_b_c(Y_train)
mu, b, c, valid_rmse = fit_model_no_UV(
    Y_csr, Y_csc, mu, b, c, lambda_bias, valid_data, 1e-5, info=2
)

original valid rmse: 1.7860372964922988
counter=1, max_norm_diff=111.8991713866579, valid_rmse=1.5794323601860292, valid_rmse_diff=0.20660493630626964
counter=2, max_norm_diff=16.108281174398396, valid_rmse=1.5644711116060812, valid_rmse_diff=0.014961248579947961
counter=3, max_norm_diff=2.2115732036853477, valid_rmse=1.5634312022543255, valid_rmse_diff=0.0010399093517556857
counter=4, max_norm_diff=1.079842766197419, valid_rmse=1.5630778316780685, valid_rmse_diff=0.0003533705762570616
counter=5, max_norm_diff=0.7986767524302414, valid_rmse=1.5628368481666877, valid_rmse_diff=0.000240983511380799
counter=6, max_norm_diff=0.6279593267796958, valid_rmse=1.562651124666763, valid_rmse_diff=0.00018572349992473924
counter=7, max_norm_diff=0.5432874637838129, valid_rmse=1.5625071497054592, valid_rmse_diff=0.00014397496130369447
counter=8, max_norm_diff=0.4570386727169688, valid_rmse=1.5623962827293951, valid_rmse_diff=0.00011086697606410567
counter=9, max_norm_diff=0.37696025350172585, valid_rmse=1.562311334448134, valid_rmse_diff=8.494828126104359e-05
counter=10, max_norm_diff=0.3064112963345825, valid_rmse=1.5622464033713903, valid_rmse_diff=6.49310767437683e-05
counter=11, max_norm_diff=0.2463080331769344, valid_rmse=1.5621968071568588, valid_rmse_diff=4.959621453148877e-05
counter=12, max_norm_diff=0.19627676350399667, valid_rmse=1.5621589140239758, valid_rmse_diff=3.789313288304896e-05
counter=13, max_norm_diff=0.15532580534487597, valid_rmse=1.562129942053723, valid_rmse_diff=2.8971970252866797e-05
counter=14, max_norm_diff=0.12223063402534029, valid_rmse=1.5621077728191526, valid_rmse_diff=2.2169234570323937e-05
counter=15, max_norm_diff=0.09574637849222153, valid_rmse=1.5620907962183177, valid_rmse_diff=1.6976600834883726e-05
counter=16, max_norm_diff=0.07471684306799375, valid_rmse=1.5620777881219428, valid_rmse_diff=1.30080963749446e-05
counter=17, max_norm_diff=0.058122652415562234, valid_rmse=1.5620678165488926, valid_rmse_diff=9.971573050160387e-06
results: counter=17, max_norm_diff=0.058122652415562234, valid_rmse=1.5620678165488926, valid_rmse_diff=9.971573050160387e-06

In [21]:
test_preds = np.clip(mu + b[test_data.rows] + c[test_data.cols], 1, 10)
test_rmse = get_rmse(test_preds, test_data)
print("test rmse of a tuned model with only biases:", test_rmse)
# test rmse of a tuned model with only biases: 1.5704328421158182

test rmse of a tuned model with only biases: 1.569357938911514

## Full model

### k=1

In [46]:
k = 1
lambda_bias = 4.5
lambda_fact = 24
mu, b, c = initialize_mu_b_c(Y_train)
rng = np.random.default_rng(seed=123)
U = rng.uniform(-20, 20, size=(Y.shape[0], k))
V = rng.uniform(-20, 20, size=(Y.shape[1], k))
mu, b, c, U, V, valid_rmse = fit_model_full(
    Y_csr, Y_csc, mu, b, c, U, V, lambda_bias, lambda_fact, valid_data, 1e-5, info=2
)

original valid rmse: 5.200346792260443
counter=1, max_norm_diff=4196.097502560533, valid_rmse=5.004227552828167, valid_rmse_diff=0.19611923943227616
counter=2, max_norm_diff=3628.36043999737, valid_rmse=3.7598827200678535, valid_rmse_diff=1.244344832760313
counter=3, max_norm_diff=776.9561399610296, valid_rmse=2.062813273336481, valid_rmse_diff=1.6970694467313727
counter=4, max_norm_diff=170.03830631254138, valid_rmse=1.6074476556137247, valid_rmse_diff=0.4553656177227561
counter=5, max_norm_diff=36.689986638881535, valid_rmse=1.5656502620985917, valid_rmse_diff=0.04179739351513301
counter=6, max_norm_diff=8.114800127368282, valid_rmse=1.5632452925234304, valid_rmse_diff=0.002404969575161342
counter=7, max_norm_diff=1.8876970972432068, valid_rmse=1.5628344714446154, valid_rmse_diff=0.0004108210788149602
counter=8, max_norm_diff=1.462411370457636, valid_rmse=1.5625971197543558, valid_rmse_diff=0.000237351690259624
counter=9, max_norm_diff=1.281137005863865, valid_rmse=1.5624635135532539, valid_rmse_diff=0.00013360620110192123
counter=10, max_norm_diff=0.7633210917056625, valid_rmse=1.5623686987432528, valid_rmse_diff=9.481481000106484e-05
counter=11, max_norm_diff=0.48704820011910893, valid_rmse=1.5623047757300879, valid_rmse_diff=6.392301316493487e-05
counter=12, max_norm_diff=0.3952740733883015, valid_rmse=1.5622655539421786, valid_rmse_diff=3.9221787909271555e-05
counter=13, max_norm_diff=0.35625630658097746, valid_rmse=1.5622419051599774, valid_rmse_diff=2.364878220117994e-05
counter=14, max_norm_diff=0.33987026453040337, valid_rmse=1.5622273842095589, valid_rmse_diff=1.4520950418539513e-05
counter=15, max_norm_diff=0.3435089845048241, valid_rmse=1.5622180099989176, valid_rmse_diff=9.374210641288627e-06
results: counter=15, max_norm_diff=0.3435089845048241, valid_rmse=1.5622180099989176, valid_rmse_diff=9.374210641288627e-06

In [23]:
biases = mu + b[test_data.rows] + c[test_data.cols]
preds = np.clip(biases + np.sum(U[test_data.rows] * V[test_data.cols], axis=1), 1, 10)
print("test rmse of full model:", get_rmse(preds, test_data))
# test rmse of full model: 1.5704970647787702

test rmse of full model: 1.5697468577018228

### k=2

In [24]:
k = 2
lambda_bias = 4.5
lambda_fact = 18.5
mu, b, c = initialize_mu_b_c(Y_train)
rng = np.random.default_rng(seed=123)
U = rng.uniform(-20, 20, size=(Y.shape[0], k))
V = rng.uniform(-20, 20, size=(Y.shape[1], k))
mu, b, c, U, V, valid_rmse = fit_model_full(
    Y_csr, Y_csc, mu, b, c, U, V, lambda_bias, lambda_fact, valid_data, 1e-5, info=2
)

original valid rmse: 5.26842318122828
counter=1, max_norm_diff=5980.984765539763, valid_rmse=5.136944531987756, valid_rmse_diff=0.131478649240524
counter=2, max_norm_diff=4866.252770195093, valid_rmse=4.398546405905988, valid_rmse_diff=0.7383981260817674
counter=3, max_norm_diff=1217.745830101025, valid_rmse=2.834022965346443, valid_rmse_diff=1.5645234405595456
counter=4, max_norm_diff=352.6216291781646, valid_rmse=1.8720837441730722, valid_rmse_diff=0.9619392211733706
counter=5, max_norm_diff=85.49647882896407, valid_rmse=1.6345849799680587, valid_rmse_diff=0.23749876420501348
counter=6, max_norm_diff=22.55733188325376, valid_rmse=1.587249210441995, valid_rmse_diff=0.047335769526063665
counter=7, max_norm_diff=8.19903583047565, valid_rmse=1.573517320513076, valid_rmse_diff=0.013731889928919161
counter=8, max_norm_diff=4.399107554092891, valid_rmse=1.5667381126237168, valid_rmse_diff=0.006779207889359151
counter=9, max_norm_diff=2.9115678748342027, valid_rmse=1.5644062657522302, valid_rmse_diff=0.002331846871486576
counter=10, max_norm_diff=1.986336168602123, valid_rmse=1.5637579481783017, valid_rmse_diff=0.0006483175739284697
counter=11, max_norm_diff=1.3926055090107645, valid_rmse=1.5635850011955787, valid_rmse_diff=0.00017294698272296571
counter=12, max_norm_diff=1.0860568018840229, valid_rmse=1.563516502912658, valid_rmse_diff=6.849828292065929e-05
counter=13, max_norm_diff=0.926943761770672, valid_rmse=1.5634786080462937, valid_rmse_diff=3.789486636440742e-05
counter=14, max_norm_diff=0.8231577378336264, valid_rmse=1.5634599864757566, valid_rmse_diff=1.8621570537113996e-05
counter=15, max_norm_diff=0.7324630286075787, valid_rmse=1.5634519006968013, valid_rmse_diff=8.085778955280176e-06
results: counter=15, max_norm_diff=0.7324630286075787, valid_rmse=1.5634519006968013, valid_rmse_diff=8.085778955280176e-06

In [25]:
biases = mu + b[test_data.rows] + c[test_data.cols]
preds = np.clip(biases + np.sum(U[test_data.rows] * V[test_data.cols], axis=1), 1, 10)
print("test rmse of full model:", get_rmse(preds, test_data))
# test rmse of full model: 1.5717291565825728

test rmse of full model: 1.5710564409801586

### k=4

In [26]:
k = 4
lambda_bias = 4.6
lambda_fact = 25
mu, b, c = initialize_mu_b_c(Y_train)
rng = np.random.default_rng(seed=123)
U = rng.uniform(-20, 20, size=(Y.shape[0], k))
V = rng.uniform(-20, 20, size=(Y.shape[1], k))
mu, b, c, U, V, valid_rmse = fit_model_full(
    Y_csr, Y_csc, mu, b, c, U, V, lambda_bias, lambda_fact, valid_data, 1e-5, info=2
)

original valid rmse: 5.328378495002235
counter=1, max_norm_diff=8327.671562612119, valid_rmse=5.264240101841594, valid_rmse_diff=0.06413839316064074
counter=2, max_norm_diff=6506.588552270267, valid_rmse=4.843696809279218, valid_rmse_diff=0.42054329256237555
counter=3, max_norm_diff=1828.4429638439728, valid_rmse=3.6896992282602343, valid_rmse_diff=1.153997581018984
counter=4, max_norm_diff=643.7440882652305, valid_rmse=2.3579880132594657, valid_rmse_diff=1.3317112150007686
counter=5, max_norm_diff=199.04066578392656, valid_rmse=1.787408797646178, valid_rmse_diff=0.5705792156132876
counter=6, max_norm_diff=60.470250815720114, valid_rmse=1.6190008342707372, valid_rmse_diff=0.16840796337544095
counter=7, max_norm_diff=20.65640092816946, valid_rmse=1.57419137613609, valid_rmse_diff=0.044809458134647207
counter=8, max_norm_diff=9.283560850578672, valid_rmse=1.564524321795132, valid_rmse_diff=0.009667054340958048
counter=9, max_norm_diff=5.008402018255848, valid_rmse=1.5636605859219113, valid_rmse_diff=0.000863735873220639
counter=10, max_norm_diff=3.300466359381549, valid_rmse=1.5630552661709505, valid_rmse_diff=0.0006053197509607866
counter=11, max_norm_diff=1.820430473377178, valid_rmse=1.5622157868528528, valid_rmse_diff=0.0008394793180976912
counter=12, max_norm_diff=1.0206336526227104, valid_rmse=1.561980590812773, valid_rmse_diff=0.0002351960400797104
counter=13, max_norm_diff=0.3794384872032579, valid_rmse=1.561914075313581, valid_rmse_diff=6.65154991921213e-05
counter=14, max_norm_diff=0.27761188852958024, valid_rmse=1.5618789525638583, valid_rmse_diff=3.5122749722615865e-05
counter=15, max_norm_diff=0.22758320096337598, valid_rmse=1.5618548707554984, valid_rmse_diff=2.4081808359888157e-05
counter=16, max_norm_diff=0.19796836979974441, valid_rmse=1.5618373120517113, valid_rmse_diff=1.7558703787168284e-05
counter=17, max_norm_diff=0.17894495386540454, valid_rmse=1.5618241729000792, valid_rmse_diff=1.3139151632035606e-05
counter=18, max_norm_diff=0.16606760610238336, valid_rmse=1.5618141738920104, valid_rmse_diff=9.99900806886167e-06
results: counter=18, max_norm_diff=0.16606760610238336, valid_rmse=1.5618141738920104, valid_rmse_diff=9.99900806886167e-06

In [27]:
biases = mu + b[test_data.rows] + c[test_data.cols]
preds = np.clip(biases + np.sum(U[test_data.rows] * V[test_data.cols], axis=1), 1, 10)
print("test rmse of full model:", get_rmse(preds, test_data))
# test rmse of full model: 1.5703045287839543

test rmse of full model: 1.5693454981767465

### k=8

In [28]:
k = 8
lambda_bias = 4.4
lambda_fact = 20
mu, b, c = initialize_mu_b_c(Y_train)
rng = np.random.default_rng(seed=123)
U = rng.uniform(-20, 20, size=(Y.shape[0], k))
V = rng.uniform(-20, 20, size=(Y.shape[1], k))
mu, b, c, U, V, valid_rmse = fit_model_full(
    Y_csr, Y_csc, mu, b, c, U, V, lambda_bias, lambda_fact, valid_data, 1e-5, info=2
)

original valid rmse: 5.286425315355606
counter=1, max_norm_diff=12084.523609148922, valid_rmse=5.180715772492115, valid_rmse_diff=0.1057095428634911
counter=2, max_norm_diff=8316.54377761616, valid_rmse=4.999188317768289, valid_rmse_diff=0.1815274547238257
counter=3, max_norm_diff=2829.367136137436, valid_rmse=4.531021859949177, valid_rmse_diff=0.4681664578191125
counter=4, max_norm_diff=1223.9754200946968, valid_rmse=3.6911469764806855, valid_rmse_diff=0.8398748834684913
counter=5, max_norm_diff=590.742536072497, valid_rmse=2.813141221769596, valid_rmse_diff=0.8780057547110895
counter=6, max_norm_diff=283.03522983290924, valid_rmse=2.2067220179475986, valid_rmse_diff=0.6064192038219973
counter=7, max_norm_diff=129.92892822389055, valid_rmse=1.8673176516977366, valid_rmse_diff=0.33940436624986203
counter=8, max_norm_diff=57.64667373190636, valid_rmse=1.7136171616535478, valid_rmse_diff=0.15370049004418873
counter=9, max_norm_diff=33.3137730579441, valid_rmse=1.629615376266441, valid_rmse_diff=0.0840017853871069
counter=10, max_norm_diff=18.860688046695742, valid_rmse=1.5894210534884714, valid_rmse_diff=0.04019432277796953
counter=11, max_norm_diff=10.49867124795189, valid_rmse=1.5721225543830493, valid_rmse_diff=0.017298499105422138
counter=12, max_norm_diff=5.685711993373514, valid_rmse=1.5658890677449249, valid_rmse_diff=0.006233486638124397
counter=13, max_norm_diff=3.597014238199753, valid_rmse=1.5632156678521856, valid_rmse_diff=0.002673399892739292
counter=14, max_norm_diff=2.14423828008432, valid_rmse=1.5624988985013264, valid_rmse_diff=0.000716769350859181
counter=15, max_norm_diff=1.2918377240164876, valid_rmse=1.56248672306774, valid_rmse_diff=1.2175433586447681e-05
counter=16, max_norm_diff=0.8846458981230794, valid_rmse=1.562568628696044, valid_rmse_diff=-8.190562830412418e-05
valid_rmse_diff is negative, returning the last iteration's values
results: counter=15, max_norm_diff=1.2918377240164876, valid_rmse=1.562568628696044, valid_rmse_diff=1.2175433586447681e-05

In [29]:
biases = mu + b[test_data.rows] + c[test_data.cols]
preds = np.clip(biases + np.sum(U[test_data.rows] * V[test_data.cols], axis=1), 1, 10)
print("test rmse of full model:", get_rmse(preds, test_data))
# test rmse of full model: 1.5702971262712437

test rmse of full model: 1.5691587253662032

### k=16

In [30]:
k = 16
lambda_bias = 4.3
lambda_fact = 14.7
mu, b, c = initialize_mu_b_c(Y_train)
rng = np.random.default_rng(seed=123)
U = rng.uniform(-20, 20, size=(Y.shape[0], k))
V = rng.uniform(-20, 20, size=(Y.shape[1], k))
mu, b, c, U, V, valid_rmse = fit_model_full(
    Y_csr, Y_csc, mu, b, c, U, V, lambda_bias, lambda_fact, valid_data, 1e-5, info=2
)

original valid rmse: 5.345172413957367
counter=1, max_norm_diff=17430.70306394037, valid_rmse=5.254492310073458, valid_rmse_diff=0.09068010388390846
counter=2, max_norm_diff=10511.998499738798, valid_rmse=5.158187602111118, valid_rmse_diff=0.09630470796234025
counter=3, max_norm_diff=4333.0093277209535, valid_rmse=5.009912677712762, valid_rmse_diff=0.14827492439835588
counter=4, max_norm_diff=1931.5198729163121, valid_rmse=4.737029804201116, valid_rmse_diff=0.2728828735116462
counter=5, max_norm_diff=988.5325735782287, valid_rmse=4.330513550514643, valid_rmse_diff=0.4065162536864735
counter=6, max_norm_diff=615.8771256305256, valid_rmse=3.8248553744014293, valid_rmse_diff=0.5056581761132133
counter=7, max_norm_diff=410.31853895476394, valid_rmse=3.330514171455027, valid_rmse_diff=0.49434120294640227
counter=8, max_norm_diff=281.22024627285634, valid_rmse=2.9049718827206035, valid_rmse_diff=0.42554228873442357
counter=9, max_norm_diff=192.81038254195488, valid_rmse=2.549717593577501, valid_rmse_diff=0.3552542891431023
counter=10, max_norm_diff=129.60425341895282, valid_rmse=2.261781573096183, valid_rmse_diff=0.28793602048131817
counter=11, max_norm_diff=84.49283397725374, valid_rmse=2.055776290378878, valid_rmse_diff=0.2060052827173049
counter=12, max_norm_diff=53.12176747133501, valid_rmse=1.910303368408944, valid_rmse_diff=0.145472921969934
counter=13, max_norm_diff=32.62864223376737, valid_rmse=1.8098122933606366, valid_rmse_diff=0.10049107504830745
counter=14, max_norm_diff=23.47425913228268, valid_rmse=1.7473720238708141, valid_rmse_diff=0.06244026948982251
counter=15, max_norm_diff=18.17521774386936, valid_rmse=1.7107557418188593, valid_rmse_diff=0.036616282051954885
counter=16, max_norm_diff=14.231129995999906, valid_rmse=1.6829398991874032, valid_rmse_diff=0.02781584263145609
counter=17, max_norm_diff=11.324187094533405, valid_rmse=1.6624199850598533, valid_rmse_diff=0.020519914127549832
counter=18, max_norm_diff=9.151706743270838, valid_rmse=1.6461187404440896, valid_rmse_diff=0.016301244615763766
counter=19, max_norm_diff=7.668018110988541, valid_rmse=1.6323848470942084, valid_rmse_diff=0.013733893349881177
counter=20, max_norm_diff=6.578306431758516, valid_rmse=1.616658904036127, valid_rmse_diff=0.015725943058081393
counter=21, max_norm_diff=5.557979328140486, valid_rmse=1.6033259733946494, valid_rmse_diff=0.013332930641477558
counter=22, max_norm_diff=4.582879111314226, valid_rmse=1.5899748255107253, valid_rmse_diff=0.013351147883924108
counter=23, max_norm_diff=3.9440936184352364, valid_rmse=1.5786805568012432, valid_rmse_diff=0.011294268709482136
counter=24, max_norm_diff=3.4294711335752646, valid_rmse=1.5704776966133955, valid_rmse_diff=0.00820286018784766
counter=25, max_norm_diff=2.9449644280413074, valid_rmse=1.5660214196171904, valid_rmse_diff=0.0044562769962051
counter=26, max_norm_diff=2.449967298443494, valid_rmse=1.5641453260530727, valid_rmse_diff=0.0018760935641177756
counter=27, max_norm_diff=1.9392043891729203, valid_rmse=1.5635908963229832, valid_rmse_diff=0.0005544297300894563
counter=28, max_norm_diff=1.4477337942157802, valid_rmse=1.56347400485985, valid_rmse_diff=0.00011689146313309529
counter=29, max_norm_diff=1.169582152350938, valid_rmse=1.5634163119678597, valid_rmse_diff=5.7692891990424044e-05
counter=30, max_norm_diff=1.027714359996197, valid_rmse=1.5633573258864097, valid_rmse_diff=5.8986081449941e-05
counter=31, max_norm_diff=0.9377538497112258, valid_rmse=1.563300959877606, valid_rmse_diff=5.636600880376541e-05
counter=32, max_norm_diff=0.8701377511399562, valid_rmse=1.5632501815829674, valid_rmse_diff=5.077829463862038e-05
counter=33, max_norm_diff=0.8145700991198666, valid_rmse=1.5632058587905202, valid_rmse_diff=4.4322792447148984e-05
counter=34, max_norm_diff=0.7668010943211215, valid_rmse=1.5631679412109727, valid_rmse_diff=3.791757954751951e-05
counter=35, max_norm_diff=0.7246900766288684, valid_rmse=1.5631360820090452, valid_rmse_diff=3.1859201927497693e-05
counter=36, max_norm_diff=0.6869846840159675, valid_rmse=1.5631088983926202, valid_rmse_diff=2.7183616424952817e-05
counter=37, max_norm_diff=0.6528740212732187, valid_rmse=1.5630855056535236, valid_rmse_diff=2.3392739096683712e-05
counter=38, max_norm_diff=0.6217934564397679, valid_rmse=1.5630668009190187, valid_rmse_diff=1.8704734504826348e-05
counter=39, max_norm_diff=0.5933268437916419, valid_rmse=1.5630524293905408, valid_rmse_diff=1.4371528477941098e-05
counter=40, max_norm_diff=0.5671529029239646, valid_rmse=1.5630419680319065, valid_rmse_diff=1.0461358634250573e-05
counter=41, max_norm_diff=0.5430140997847872, valid_rmse=1.563034991188172, valid_rmse_diff=6.9768437345185674e-06
results: counter=41, max_norm_diff=0.5430140997847872, valid_rmse=1.563034991188172, valid_rmse_diff=6.9768437345185674e-06

In [31]:
biases = mu + b[test_data.rows] + c[test_data.cols]
preds = np.clip(biases + np.sum(U[test_data.rows] * V[test_data.cols], axis=1), 1, 10)
print("test rmse of full model:", get_rmse(preds, test_data))
# test rmse of full model: 1.5717814048614096

test rmse of full model: 1.5703207806790256

### k=32

In [39]:
k = 32
lambda_bias = 4.3
lambda_fact = 13.7
mu, b, c = initialize_mu_b_c(Y_train)
rng = np.random.default_rng(seed=123)
U = rng.uniform(-20, 20, size=(Y.shape[0], k))
V = rng.uniform(-20, 20, size=(Y.shape[1], k))
mu, b, c, U, V, valid_rmse = fit_model_full(
    Y_csr, Y_csc, mu, b, c, U, V, lambda_bias, lambda_fact, valid_data, 1e-5, info=2
)

original valid rmse: 5.337447834544822
counter=1, max_norm_diff=24650.981228178964, valid_rmse=5.320372901788236, valid_rmse_diff=0.01707493275658578
counter=2, max_norm_diff=14090.656731221077, valid_rmse=5.255172633018755, valid_rmse_diff=0.06520026876948126
counter=3, max_norm_diff=6077.296198599668, valid_rmse=5.173133376992354, valid_rmse_diff=0.08203925602640094
counter=4, max_norm_diff=2916.016825454374, valid_rmse=5.035764407050613, valid_rmse_diff=0.13736896994174064
counter=5, max_norm_diff=1529.6968034811475, valid_rmse=4.849850860972617, valid_rmse_diff=0.18591354607799637
counter=6, max_norm_diff=880.6693697897409, valid_rmse=4.611443732550428, valid_rmse_diff=0.23840712842218892
counter=7, max_norm_diff=561.100232536628, valid_rmse=4.340471074276901, valid_rmse_diff=0.2709726582735268
counter=8, max_norm_diff=407.03052042584426, valid_rmse=4.067656897079272, valid_rmse_diff=0.27281417719762935
counter=9, max_norm_diff=310.873188919184, valid_rmse=3.8011889677134163, valid_rmse_diff=0.2664679293658554
counter=10, max_norm_diff=246.2031511937509, valid_rmse=3.517364108001463, valid_rmse_diff=0.28382485971195326
counter=11, max_norm_diff=199.72361513560674, valid_rmse=3.230458981538435, valid_rmse_diff=0.286905126463028
counter=12, max_norm_diff=164.3495988312835, valid_rmse=2.9610920670847545, valid_rmse_diff=0.26936691445368055
counter=13, max_norm_diff=136.0280099210799, valid_rmse=2.718200691642783, valid_rmse_diff=0.24289137544197148
counter=14, max_norm_diff=112.27775457220115, valid_rmse=2.505975785624398, valid_rmse_diff=0.21222490601838517
counter=15, max_norm_diff=91.82495235109327, valid_rmse=2.33583980980815, valid_rmse_diff=0.17013597581624795
counter=16, max_norm_diff=74.14895586005534, valid_rmse=2.198514976485105, valid_rmse_diff=0.1373248333230448
counter=17, max_norm_diff=59.02454693588313, valid_rmse=2.0758616952140834, valid_rmse_diff=0.12265328127102171
counter=18, max_norm_diff=46.25066200141284, valid_rmse=1.96535977675216, valid_rmse_diff=0.11050191846192337
counter=19, max_norm_diff=35.58994657002588, valid_rmse=1.8697195195612537, valid_rmse_diff=0.0956402571909063
counter=20, max_norm_diff=26.880870692996158, valid_rmse=1.790607587180019, valid_rmse_diff=0.07911193238123482
counter=21, max_norm_diff=21.66985880718685, valid_rmse=1.7325166543026898, valid_rmse_diff=0.05809093287732914
counter=22, max_norm_diff=17.259313733138207, valid_rmse=1.6940842325762908, valid_rmse_diff=0.038432421726398935
counter=23, max_norm_diff=13.782433665973475, valid_rmse=1.6666139044184956, valid_rmse_diff=0.027470328157795265
counter=24, max_norm_diff=11.10373101769557, valid_rmse=1.6408366183968361, valid_rmse_diff=0.025777286021659407
counter=25, max_norm_diff=8.92889785325701, valid_rmse=1.6247225126412044, valid_rmse_diff=0.01611410575563177
counter=26, max_norm_diff=7.275748393534011, valid_rmse=1.6137368447695795, valid_rmse_diff=0.010985667871624916
counter=27, max_norm_diff=6.0939300622250885, valid_rmse=1.605058257301199, valid_rmse_diff=0.00867858746838035
counter=28, max_norm_diff=5.24504117440937, valid_rmse=1.5970543313397578, valid_rmse_diff=0.008003925961441283
counter=29, max_norm_diff=4.512229438950492, valid_rmse=1.5907742555061903, valid_rmse_diff=0.006280075833567489
counter=30, max_norm_diff=3.8263556050005003, valid_rmse=1.5860539423213151, valid_rmse_diff=0.004720313184875202
counter=31, max_norm_diff=3.2508290389965113, valid_rmse=1.582147964969759, valid_rmse_diff=0.003905977351556178
counter=32, max_norm_diff=2.884631189632918, valid_rmse=1.5791399522884033, valid_rmse_diff=0.003008012681355643
counter=33, max_norm_diff=2.5996001184175808, valid_rmse=1.574061236009049, valid_rmse_diff=0.005078716279354412
counter=34, max_norm_diff=2.30917382829928, valid_rmse=1.568722966933432, valid_rmse_diff=0.005338269075616964
counter=35, max_norm_diff=2.1096617058814893, valid_rmse=1.565320079074836, valid_rmse_diff=0.003402887858595882
counter=36, max_norm_diff=1.962774171289556, valid_rmse=1.563346094138033, valid_rmse_diff=0.0019739849368030082
counter=37, max_norm_diff=1.7241104870296695, valid_rmse=1.5623694031777353, valid_rmse_diff=0.0009766909602977325
counter=38, max_norm_diff=1.452765561327642, valid_rmse=1.5620008447712914, valid_rmse_diff=0.00036855840644389737
counter=39, max_norm_diff=1.1801321904390893, valid_rmse=1.5618996059242913, valid_rmse_diff=0.00010123884700008468
counter=40, max_norm_diff=0.9938225857967743, valid_rmse=1.5618738405331223, valid_rmse_diff=2.576539116905252e-05
counter=41, max_norm_diff=0.8882059048415888, valid_rmse=1.5618654245586538, valid_rmse_diff=8.415974468434229e-06
results: counter=41, max_norm_diff=0.8882059048415888, valid_rmse=1.5618654245586538, valid_rmse_diff=8.415974468434229e-06

In [41]:
biases = mu + b[test_data.rows] + c[test_data.cols]
preds = np.clip(biases + np.sum(U[test_data.rows] * V[test_data.cols], axis=1), 1, 10)
print("test rmse of full model:", get_rmse(preds, test_data))
# test rmse of full model: 1.5699819711228356

test rmse of full model: 1.5696710384371007

### k=256

In [ ]:
k = 256
lambda_bias = 4
lambda_fact = 10
mu, b, c = initialize_mu_b_c(Y_train)
rng = np.random.default_rng(seed=123)
U = rng.uniform(-20, 20, size=(Y.shape[0], k))
V = rng.uniform(-20, 20, size=(Y.shape[1], k))
mu, b, c, U, V, valid_rmse = fit_model_full(
    Y_csr, Y_csc, mu, b, c, U, V, lambda_bias, lambda_fact, valid_data, 1e-5, info=2
)

In [35]:
biases = mu + b[test_data.rows] + c[test_data.cols]
preds = np.clip(biases + np.sum(U[test_data.rows] * V[test_data.cols], axis=1), 1, 10)
print("test rmse of full model:", get_rmse(preds, test_data))
# test rmse of full model: 1.568533842304493

test rmse of full model: 1.5716560890330094

### k=512

In [36]:
k = 512
lambda_bias = 3.9
lambda_fact = 10
mu, b, c = initialize_mu_b_c(Y_train)
rng = np.random.default_rng(seed=123)
U = rng.uniform(-20, 20, size=(Y.shape[0], k))
V = rng.uniform(-20, 20, size=(Y.shape[1], k))
mu, b, c, U, V, valid_rmse = fit_model_full(
    Y_csr, Y_csc, mu, b, c, U, V, lambda_bias, lambda_fact, valid_data, 1e-5, info=2
)

original valid rmse: 5.351797414533016
counter=1, max_norm_diff=103753.03410204069, valid_rmse=5.313275834547766, valid_rmse_diff=0.0385215799852503
counter=2, max_norm_diff=55701.10674297039, valid_rmse=5.299997366789243, valid_rmse_diff=0.01327846775852315
counter=3, max_norm_diff=25057.79421235973, valid_rmse=5.316870949300243, valid_rmse_diff=-0.016873582510999796
valid_rmse_diff is negative, returning the last iteration's values
results: counter=2, max_norm_diff=55701.10674297039, valid_rmse=5.316870949300243, valid_rmse_diff=0.01327846775852315

In [37]:
biases = mu + b[test_data.rows] + c[test_data.cols]
preds = np.clip(biases + np.sum(U[test_data.rows] * V[test_data.cols], axis=1), 1, 10)
print("test rmse of full model:", get_rmse(preds, test_data))
# test rmse of full model: 1.5690911174883715

test rmse of full model: 5.3084382077888

In [38]:
# seed = 103
# global mean                           test_rmse = 1.8087624016357353
# only biases                           test_rmse = 1.5704328421158182
# k = 1,   l_bias = 4.5, l_fact = 24,   test_rmse = 1.5704970647787702
# k = 2,   l_bias = 4.5, l_fact = 18.5, test_rmse = 1.5717291565825728
# k = 4,   l_bias = 4.6, l_fact = 25,   test_rmse = 1.5703045287839543
# k = 8,   l_bias = 4.4, l_fact = 20,   test_rmse = 1.5702971262712437
# k = 16,  l_bias = 4.3, l_fact = 14.7, test_rmse = 1.5717814048614096
# k = 32,  l_bias = 4.3, l_fact = 13.7, test_rmse = 1.5699819711228356
# k = 256, l_bias = 4,   l_fact = 10    test_rmse = 1.568533842304493
# k = 512, l_bias = 3.9, l_fact = 10,   test_rmse = 1.5690911174883715